### ISSUE TITLE
Rajetic read this

### ISSUE THREAD

**Issue by 0Xandon0** [rajetic/auto_oculus_touch#16]
@rajetic you need to fix your code I spent an hour learning C++ then SEVERAL hours debugging your code to figure out what was wrong and when I tell you the problem you do not respond. Could you implement the fix I discovered or add me as collaborator since I am an active developer. The problem in the code was the drivermatch function which is unnecessary and broken. I would also continue to develop AOT if I was a contributor.

**Comment by rajetic** [comment]
You reported some issues. I gave a 408 word response, fixed the problems and released a new version 3 months ago. I even added in extra sdk files just for you because you had trouble setting the project up.

If there's still a problem with the fixes I made for you, what are they?
