### ISSUE TITLE
What is the enum for the menu button on the left Touch controller?

### ISSUE THREAD

**Issue by FolkSong** [rajetic/auto_oculus_touch#4]
I don't see it listed.

**Comment by rajetic** [comment]
ovrEnter.
The oculus sdk use ovrEnter for the centre button on the oculus remote, the menu button on the left touch and the menu button on the xbox controller.

(I really should comment those, I just copied the names from the sdk, but they aren't always obvious without reading the sdk header).

**Comment by FolkSong** [comment]
Thanks, I didn't think to try that one.

**Comment by FolkSong** [comment]
This is a very useful tool by the way, thanks for releasing it!
