### ISSUE TITLE
Enums for capacitive sensors are identical to enums for button presses

### ISSUE THREAD

**Issue by FolkSong** [rajetic/auto_oculus_touch#5]
Nevermind

**Comment by rajetic** [comment]
No prob. :)
The sdk doubles up on the values for some buttons, but there's some buttons with no touch equivalent and some touch (like the rest pad) with no button equivalent. So I kept the naming scheme they used.

**Comment by FolkSong** [comment]
I'll change the title back so if anyone else gets confused like I did they might find this.
