### ISSUE TITLE
Completely broken after recent Oculus update

### ISSUE THREAD

**Issue by shdwp** [rajetic/auto_oculus_touch#9]
Sadly they broke it in the update. No buttons are working now.

**Comment by Kiroorik** [comment]
confirmed this issue on my end as well :(
I wonder if its possible to use a Unity script and call out OVRInput for the controller status?

**Comment by Kiroorik** [comment]
https://developer.oculus.com/documentation/unity/latest/concepts/unity-ovrinput/?_fb_noscript=1

**Comment by booty156** [comment]
recompiled dll file, working fine with lastest updates!

https://drive.google.com/open?id=16FPF1JH3HZ5WMdgpHs1VuNSuBkrGZQZ5

credit to mateuzdrawl

**Comment by rajetic** [comment]
Runtime 1.29 (currently in beta release) fixes the bug. Yay!
No need to recompile, the current version of AutoOculusTouch works again.
